[package]
name = "widen"
version = "0.1.0"
edition = "2021"
rust-version = "1.71"
description = "Error unions and widening conversions for ordinary Rust enums"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sshockwave/widen"
keywords = ["error", "error-handling", "enum", "union", "no-std"]
categories = ["rust-patterns", "no-std"]
exclude = [".github/"]

[workspace]
resolver = "2"
members = ["derive"]

[features]
default = ["derive"]
derive = ["dep:widen-derive"]

[dependencies]
widen-derive = { version = "0.1.0", path = "derive", optional = true }

[dev-dependencies]
thiserror = "2"
trybuild = "1"
