[package]
name = "widen-derive"
version = "0.1.1"
edition = "2021"
rust-version = "1.71"
description = "Derive support for widen"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sshockwave/widen"
keywords = ["error", "error-handling", "enum", "union", "derive"]
categories = ["rust-patterns"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
syn = "3"
