#![no_std]
#![forbid(unsafe_code)]
#![cfg_attr(feature = "derive", doc = include_str!("../README.md"))]

//! # Common patterns
//!
//! ## Error unions with thiserror
//!
//! `thiserror::Error` supplies `Display`, `Error`, and the payload `From`
//! implementations generated by `#[from]`. Deriving `Widen` on the smaller enum
//! lets it widen into any enum that accepts those payloads. The larger enum can
//! subsume the smaller one, following the idea of subset inclusion.
//!
//! ```
//! # #[cfg(feature = "derive")]
//! # {
//! use thiserror::Error;
//! use widen::Widen;
//!
//! #[derive(Debug, Error, Widen)]
//! enum ReadError {
//!     #[error(transparent)]
//!     Parse(#[from] std::num::ParseIntError),
//! }
//!
//! #[derive(Debug, Error)]
//! enum AppError {
//!     #[error(transparent)]
//!     Parse(#[from] std::num::ParseIntError),
//!     #[error(transparent)]
//!     Io(#[from] std::io::Error),
//! }
//!
//! fn read_number(text: &str) -> Result<u32, ReadError> {
//!     Ok(text.parse()?)
//! }
//!
//! fn load(text: &str) -> Result<u32, AppError> {
//!     read_number(text).map_err(Widen::widen)
//! }
//!
//! assert_eq!(load("42").unwrap(), 42);
//! assert!(matches!(load("invalid"), Err(AppError::Parse(_))));
//! # }
//! ```
//!
//! The tail return determines the target of `map_err(Widen::widen)`. Adding `?`
//! there generally needs a type annotation; a wrapper can support `.widen()?`
//! as shown below. For unit variants or explicit variant mappings, use
//! [`#[subsume(...)]`](derive.Widen.html#explicit-variant-mappings) to generate
//! `From<Source>` implementations and propagate directly with `?`.
//!
//! ## Capturing and preserving a backtrace
//!
//! Capture a backtrace when an error first enters a wrapper. Implement `Widen`
//! for the wrapper to convert its error while preserving the original backtrace.
//!
//! ```
//! use std::backtrace::Backtrace;
//! use widen::Widen;
//!
//! #[derive(Debug)]
//! struct Traced<E> {
//!     error: E,
//!     backtrace: Backtrace,
//! }
//!
//! impl<E> From<E> for Traced<E> {
//!     fn from(error: E) -> Self {
//!         Self { error, backtrace: Backtrace::capture() }
//!     }
//! }
//!
//! impl<E: Widen<F>, F> Widen<Traced<F>> for Traced<E> {
//!     fn widen(self) -> Traced<F> {
//!         let Traced { error, backtrace } = self;
//!         Traced { error: error.widen(), backtrace }
//!     }
//! }
//!
//! fn capture<T, E>(result: Result<T, E>) -> Result<T, Traced<E>> {
//!     result.map_err(Traced::from)
//! }
//!
//! fn higher<T, E: Widen<F>, F>(result: Result<T, Traced<E>>)
//!     -> Result<T, Traced<F>>
//! {
//!     result.map_err(Widen::widen)
//! }
//!
//! # #[cfg(feature = "derive")]
//! # {
//! # #[derive(Widen)]
//! # enum Number { Byte(u8) }
//! # let result: Result<(), Traced<u32>> = higher(capture(Err(Number::Byte(42))));
//! # assert_eq!(result.unwrap_err().error, 42);
//! # }
//! ```
//!
//! `Backtrace::capture()` follows the standard backtrace environment settings,
//! including `RUST_LIB_BACKTRACE`. This recipe uses `std`; the `widen` runtime
//! itself remains `no_std`.
//!
//! ## Propagating with an error wrapper
//!
//! A wrapper supplies the receiving `From` implementation that lets `.widen()?`
//! infer the destination error type. This example uses a wrapper containing only
//! an error so the propagation mechanism stands on its own.
//!
//! ```
//! use widen::{Widen, Widening};
//!
//! #[derive(Debug)]
//! struct Wrapped<E>(E);
//!
//! impl<E> From<E> for Wrapped<E> {
//!     fn from(error: E) -> Self {
//!         Self(error)
//!     }
//! }
//!
//! impl<E: Widen<F>, F> From<Widening<Wrapped<E>, F>> for Wrapped<F> {
//!     fn from(error: Widening<Wrapped<E>, F>) -> Self {
//!         Self(error.into_inner().0.widen())
//!     }
//! }
//!
//! fn wrap<T, E>(result: Result<T, E>) -> Result<T, Wrapped<E>> {
//!     Ok(result?) // Wraps the error through From<E>.
//! }
//!
//! fn higher<T, E: Widen<F>, F>(result: Result<T, Wrapped<E>>)
//!     -> Result<T, Wrapped<F>>
//! {
//!     Ok(result.widen()?) // Infers F from the return type.
//! }
//!
//! # #[cfg(feature = "derive")]
//! # {
//! # #[derive(Widen)]
//! # enum Number { Byte(u8) }
//! # let result: Result<(), Wrapped<u32>> = higher(wrap(Err(Number::Byte(42))));
//! # assert_eq!(result.unwrap_err().0, 42);
//! # }
//! ```
//!
//! A wrapper carrying a backtrace or other context can use the same receiving
//! `From` implementation, preserving that metadata while converting the error.
//! To use explicit `subsume` mappings with this wrapper, replace `E: Widen<F>`
//! with `F: From<E>` and convert with `.into()`. See [`Widening`] for why
//! the adapter carries a target type and how its `From` implementation coexists
//! with `From<E> for Wrapped<E>`.

extern crate self as widen;

use core::{fmt, marker::PhantomData};

/// Derive payload widening or explicit enum conversions.
///
/// Implements [`trait@Widen`] when every variant contains exactly one field.
/// Independently, `#[subsume(...)]` generates incoming [`From`] implementations.
///
/// # Payload widening
///
/// Each variant must contain exactly one field. Tuple and named variants,
/// generics, lifetimes, and where clauses are supported; an empty enum can widen
/// to any target. The generated implementation requires `Target: From<Payload>`
/// for every payload type and matches each variant to convert its payload.
///
/// ```
/// use widen::Widen;
///
/// struct ParseError;
/// struct ConfigError;
///
/// #[derive(Widen)]
/// enum ReadError {
///     Parse(ParseError),
/// }
///
/// enum AppError {
///     Parse(ParseError),
///     Config(ConfigError),
/// }
///
/// impl From<ParseError> for AppError {
///     fn from(error: ParseError) -> Self {
///         Self::Parse(error)
///     }
/// }
///
/// fn promote(error: ReadError) -> AppError {
///     error.widen()
/// }
/// ```
///
/// Payload `From` implementations are supplied separately, either by hand or by
/// `thiserror::Error` with `#[from]` fields. Variant names do not participate in
/// conversion: variants with the same payload type may become indistinguishable.
/// Subset inclusion is the model; arbitrary `From` implementations may transform
/// payloads rather than preserve them.
///
/// # Explicit variant mappings
///
/// Put `#[subsume(...)]` on destination variants to flatten source enums,
/// including unit variants. Each listed source gets an exhaustive `From<Source>`
/// implementation. Source enums need no derive or helper macro.
///
/// ```
/// use widen::Widen;
///
/// enum A {
///     Shared,
///     Exclusive,
///     Normal(u32),
/// }
///
/// enum B {
///     Shared,
///     Exclusive,
///     Normal(u16),
/// }
///
/// #[derive(Debug, PartialEq, Widen)]
/// enum C {
///     #[subsume(A::Shared, B::Shared)]
///     SharedVariant,
///     #[subsume(A::Exclusive)]
///     VariantA,
///     #[subsume(B::Exclusive)]
///     VariantB,
///     #[subsume(A::Normal, from(B::Normal))]
///     Normal(u32),
/// }
///
/// assert_eq!(C::from(A::Shared), C::SharedVariant);
/// assert_eq!(C::from(B::Exclusive), C::VariantB);
/// assert_eq!(C::from(B::Normal(7)), C::Normal(7));
/// ```
///
/// - Plain mappings forward fields unchanged. `from(Source::Variant)` opts into
///   `.into()` for each field of that source variant and requires payload fields.
/// - Source and destination variants must have the same field shape: unit,
///   tuple with the same number of fields, or named with the same field names.
/// - Every variant of each listed source must be covered exactly once. Omitting
///   one is a Rust exhaustiveness error; extra destination variants are allowed.
///   Foreign `#[non_exhaustive]` enums cannot be exhaustively flattened.
/// - Generic source paths, such as `Source::<T>::Value`, and destination enums
///   are supported. Put required payload conversion bounds on the destination.
///
/// These incoming `From` implementations are independent of outgoing payload
/// widening. When every variant contains exactly one field, the derive generates
/// both. Enums with unit or multiple-field variants get only the `From`
/// implementations. Without `subsume` mappings, such variants are rejected.
/// Use `.into()` or ordinary `?` for the mapped conversions; payload-based
/// `Widen` implementations do not dispatch through them.
///
/// ```
/// use widen::Widen;
///
/// enum Small {
///     Byte(u8),
/// }
///
/// #[derive(Widen)]
/// enum Combined {
///     #[subsume(Small::Byte)]
///     Byte(u8),
///     Word(u16),
/// }
///
/// let combined = Combined::from(Small::Byte(42));
/// let value: u32 = combined.widen();
/// assert_eq!(value, 42);
/// ```
///
/// Ordinary derives and `thiserror` attributes can be combined with `subsume`.
/// For example, `#[error("{}", A::Shared)]` delegates a unit variant's display;
/// `#[from]` fields can generate additional payload conversions. Avoid generating
/// the same `From<Source>` implementation with both derives.
#[cfg(feature = "derive")]
pub use widen_derive::Widen;

/// Widen a value into a destination determined by its context.
///
/// Derived enum conversions resemble subset inclusion: a destination that accepts
/// every source payload type can subsume the source. The `Result` implementation
/// marks its error for conversion through [`Widening`].
///
/// Inclusion is a convention: arbitrary `From` implementations may transform
/// payloads, and variants with the same payload type may become indistinguishable.
///
/// An expected return type or assignment usually determines the destination.
/// `result.map_err(Widen::widen)` also works as a tail return expression, but
/// adding `?` generally requires an explicit intermediate error type because
/// `?` permits another conversion. For propagation through your own error
/// wrapper, use `result.widen()?` with the integration described in [`Widening`].
pub trait Widen<T>: Sized {
    /// Convert the value or prepare its error for conversion.
    fn widen(self) -> T;
}

/// An error awaiting conversion into a destination chosen by its receiver.
///
/// `E` is the complete source error, including any wrapper or context.
/// `Target` is a type marker with no stored value. An integration can use it
/// for the destination payload type, such as `F` in `Wrapped<F>`.
///
/// # Integrating an error wrapper
///
/// The wrapper's crate supplies the receiving `From` implementation. Individual
/// destination enums need no wrapper-specific code, and callers can use
/// `.widen()?` without target annotations. The
/// [crate-level example](crate#propagating-with-an-error-wrapper) shows this
/// integration with `Wrapped<E>`.
///
/// Keep any backtrace or other wrapper metadata in this conversion. To use
/// explicit `subsume` mappings instead of
/// payload widening, use the bound `F: From<E>` and convert with `error.into()`.
///
/// # Why the target marker exists
///
/// Including `Target` in the source type allows an implementation such as
/// `From<Widening<Wrapped<E>, F>> for Wrapped<F>` to coexist with
/// `From<E> for Wrapped<E>`. Overlap would require the impossible type equation
/// `F = Widening<Wrapped<E>, F>`. The marker occupies no space; propagation uses
/// standard `Result` and `From`, with no custom `Try` implementation.
#[must_use]
pub struct Widening<E, Target> {
    error: E,
    target: PhantomData<fn() -> Target>,
}

impl<E, Target> Widening<E, Target> {
    /// Mark an error for conversion. The receiving context can infer `Target`.
    pub const fn new(error: E) -> Self {
        Self {
            error,
            target: PhantomData,
        }
    }

    /// Recover the complete source error so an integration can convert it.
    pub fn into_inner(self) -> E {
        self.error
    }
}

impl<E: fmt::Debug, Target> fmt::Debug for Widening<E, Target> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Widening").field(&self.error).finish()
    }
}

impl<T, E, Target> Widen<Result<T, Widening<E, Target>>> for Result<T, E> {
    /// Wrap the error in [`Widening`], preserving successful values.
    ///
    /// With a compatible destination wrapper, `operation().widen()?` infers
    /// `Target` from the enclosing function's return type. This method marks
    /// the error for conversion; the receiving `From` implementation converts it.
    fn widen(self) -> Result<T, Widening<E, Target>> {
        self.map_err(Widening::new)
    }
}
